set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports Dec_Duty]
set_property PACKAGE_PIN T17 [get_ports Inc_Duty]
set_property PACKAGE_PIN A14 [get_ports PWM_Out]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports Dec_Duty]
set_property IOSTANDARD LVCMOS33 [get_ports Inc_Duty]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_Out]

set_property IOSTANDARD LVCMOS33 [get_ports decrease_duty]
set_property IOSTANDARD LVCMOS33 [get_ports increase_duty]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_OUT]
set_property PACKAGE_PIN A14 [get_ports PWM_OUT]
set_property PACKAGE_PIN T17 [get_ports increase_duty]
set_property PACKAGE_PIN W19 [get_ports decrease_duty]

set_property IOSTANDARD LVCMOS33 [get_ports dec_duty]
set_property IOSTANDARD LVCMOS33 [get_ports inc_duty]
set_property PACKAGE_PIN W19 [get_ports dec_duty]
set_property PACKAGE_PIN T17 [get_ports inc_duty]
